# The environment on which we're testing
env: 'CartPole-v1'

# Arguments passed to actor
actor:
  # List of hidden dims
  hidden:
    - 32

# Arguments passed to critic
critic:
  hidden:
    - 32
  # YAML NEEDS THE .0 TO CHECK NUMBER
  lr: 5.0e-3

# TRPO hyper-parameters
trpo:
  # Maximum allowed KL-divergence
  max_d_kl: 1.0e-2
  # Maximum line search steps
  max_ls_steps: 10
  # Factor by which to reduce step-size
  # if max_d_kl is exceeded in line search
  ls_step_coef: 0.9

# General DL training parameters
train:
  batch_size: 16
  episodes: 50

# Experimental control
run:
  experiment_name: test
  debug: True
  seed: 42
  gpu: False
  set_gpu_deterministic: True
  plot_rewards: True
  logging_frequency: 1